image: java:8-jdk

before_script:
  - echo `pwd`
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x gradlew

build:
  stage: build
  script:
    - ./gradlew build

test:
  stage: test
  script:
    - ./gradlew test

after_script:
  - echo "Fin de la integración continua"